### PR TITLE
Add more detail on data sources

### PR DESCRIPTION
**Pull request by davidread**
I always feel a bit hazy on 'data sources' on AP, so am keen to write down a description of them. App data sources are particularly scant in the docs.

@isichei I've mentioned curated buckets twice - can you clarify if they are warehouse data sources or not?

### CODE REVIEW

**Comment by calumabarnett** [comment]
Curated databases are stored in non 'alpha' buckets in S3 but are accessed solely through Athena (as far as I'm aware). On that basis, I don't think we should mention them in this section. There is more information about curated databases in the [database user guidance](https://github.com/moj-analytical-services/database_user_guidance) though this is still incomplete and hasn't been rolled out. Contrary to my original thinking, I think it might make more sense to integrate this with the main guidance and add to it as new databases become available.

**Comment by davidread** [comment]
Got you, so there are curated Athena databases. I guess that's not relevant here. Although they are backed by objects in S3.

I get the impression that there is also 'curated' CSV files in S3 buckets too though - a search brings up these as likely ones 'alpha-curated-postcodes-example-gk' and 'alpha-mojap-curated-xhibit', 'alpha-mojap-curated-mags'. So it seems I'd be correct to say:

> **Warehouse data source** ... These data sources can be created by users themselves and shared with colleagues. Alternatively they are 'curated' by the Data Engineering team.

I think you're right, the `mojap-land` bucket and others internal to Data Engineering (and indeed others that AP uses internally like Terraform state) don't need to mentioned in these docs at all, so I've removed that para.

**Comment by calumabarnett** [comment]
I'm not sure about this – it would be worth checking with @isichei:
> I get the impression that there is also 'curated' CSV files in S3 buckets too though - a search brings up these as likely ones 'alpha-curated-postcodes-example-gk' and 'alpha-mojap-curated-xhibit', 'alpha-mojap-curated-mags'.

**Comment by davidread** [comment]
Ping @isichei

**Comment by calumabarnett** [comment]
@isichei would you be able to take a look at this?

**Comment by davidread** [comment]
I've taken out the sentence on data engineers, so hopefully this is fine to merge now @calumabarnett ?

**Pull request merged**
