### PR TITLE
Fix links

### LINKED ISSUE #75: broken link to guidance on using github with Analytical Platform
The link on this line results in a 404:

https://github.com/moj-analytical-services/platform_user_guidance/blob/master/02-start.Rmd#L156

### PR DESCRIPTION
**Pull request by calumabarnett**
Fixes #75.

### CODE REVIEW

**Comment by davidread** [comment]
Do you know what the CI error is?

**Comment by calumabarnett** [comment]
@davidread This CI issue seems to be occurring for all R builds not just ours: ```The command "Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .```

**Comment by davidread** [comment]
@calumabarnett I googled it and there seems to be hope here: https://travis-ci.community/t/devtools-error-in-match-arg-upgrade-c-ask-always-never-arg-must-be-of-length-1/2940/7 . I suggest we give it a couple of days and it may resolve. If we are desperate to merge then let's do the workaround Jim suggests.

**Comment by calumabarnett** [comment]
@davidread No, I don't think we're desperate, so we can wait a few days. From speaking to Ravi, he seemed to think we should try to move off of Travis anyway. I'm going to give Circle a go on the database guidance and see if it's quicker/more stable.

**Pull request merged**
